// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccowjocpzxvirnqwutoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjb3dqb2Nwenh2aXJucXd1dG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMzI5NTQsImV4cCI6MjA4MTkwODk1NH0.rvWDsUJFaQeLAGWwRXP28jMkJjkAy81Fy3BIOQ1FBW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});